apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration
spec:
  selector:
    matchLabels:
      app: expiration
  template:
    metadata:
      labels:
        app: expiration
    spec:
      initContainers:
      - name: init-wait-for-nats
        image: alpine
        command: ["/bin/sh", "-c", "for i in $(seq 1 300); do nc -zvw1 nats-srv 4222 && exit 0 || sleep 3; done; exit 1"]
      containers:
      - name: expiration
        image: dgabka/ticketing-expiration
        ports:
        - containerPort: 3000
        env:
        - name: NATS_URL
          value: 'http://nats-srv:4222'
        - name: NATS_CLUSTER_ID
          value: 'ticketing'
        - name: NATS_CLIENT_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: REDIS_HOST
          value: 'expiration-redis-srv'
