apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments
spec:
  selector:
    matchLabels:
      app: payments
  template:
    metadata:
      labels:
        app: payments
    spec:
      containers:
      - name: payments
        image: dgabka/ticketing-payments
        ports:
        - containerPort: 3000
        env:
        - name: JWT_KEY
          valueFrom:
            secretKeyRef:
              name: jwt-secret
              key: JWT_KEY
        - name: MONGO_URI
          value: 'mongodb://payments-mongo-srv:27017/payments'
        - name: NATS_URL
          value: 'http://nats-srv:4222'
        - name: NATS_CLUSTER_ID
          value: 'ticketing'
        - name: NATS_CLIENT_ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: STRIPE_KEY
          valueFrom:
            secretKeyRef:
              key: STRIPE_KEY
              name: stripe-secret
---
apiVersion: v1
kind: Service
metadata:
  name: payments-srv
spec:
  selector:
    app: payments
  ports:
  - port: 3000
    targetPort: 3000
